<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>BigMart- online Grocery shopp</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Lora:wght@600;700&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <div class="grid grid-flow-col place-content-start gap-x-6 lg:py-1 xl:pb-2 xl:pt-3">
        <div class="Header___StyledCategoryMenu2-sc-19kl9m3-13 ibVaum">
            <div class="Backdrop___StyledDiv-sc-1mhwh2y-0 dmXkR CategoryMenu___StyledBackdrop-sc-d3svbp-0 bNLTZW">
                <div class="relative h-full" data-headlessui-state=""><button class="h-full px-2.5 lg:py-1.5 xl:py-2.5 content-center  grid grid-flow-col lg:gap-x-10.5 xl:gap-x-4.5 rounded-2xs text-white 
              bg-appleGreen-600 border border-white" id="headlessui-menu-button-:R5bclm:" type="button"
                        aria-haspopup="true" aria-expanded="false" data-headlessui-state=""
                        aria-controls="headlessui-menu-items-:R9bclm:">
                        <div
                            class="grid xl:grid-flow-col lg:grid-flow-row xl:gap-x-0.7 lg:gap-x-0 text-left leading-none">
                            <span class="Label-sc-15v1nk5-0 CategoryMenu___StyledLabel-sc-d3svbp-1 gJxZPQ gYxTYh">Shop
                                by</span><span
                                class="Label-sc-15v1nk5-0 CategoryMenu___StyledLabel2-sc-d3svbp-2 gJxZPQ mbYld">Category</span>
                        </div><svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg"
                            class="CategoryMenu___StyledArrowDown-sc-d3svbp-3 iwTeGC transform rotate-180">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                d="M8 11.333c-.338 0-.66-.155-.884-.428l-2.81-3.398a1.39 1.39 0 0 1-.172-1.474c.204-.432.608-.7 1.057-.7h5.617c.449 0 .854.268 1.057.7a1.39 1.39 0 0 1-.172 1.473l-2.81 3.4a1.146 1.146 0 0 1-.883.427Z"
                                fill="#fff"></path>
                        </svg>
                    </button>
                    <div class="CategoryMenu___StyledMenuItems-sc-d3svbp-4 cAslOa" id="headlessui-menu-items-:R9bclm:"
                        role="menu" tabindex="0" data-headlessui-state=""
                        aria-labelledby="headlessui-menu-button-:R5bclm:">
                        <nav class="jsx-1259984711 flex text-medium" role="none">
                            <ul class="jsx-1259984711 w-56 px-2.5 bg-darkOnyx-800 text-silverSurfer-100 rounded-l-xs"
                                role="none">
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 wWSyB"
                                        href="/cl/fruits-vegetables/?nc=nb" role="none">Fruits &amp; Vegetables</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/foodgrains-oil-masala/?nc=nb" role="none">Foodgrains, Oil &amp;
                                        Masala</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/bakery-cakes-dairy/?nc=nb" role="none">Bakery, Cakes &amp; Dairy</a>
                                </li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK" href="/cl/beverages/?nc=nb"
                                        role="none">Beverages</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/snacks-branded-foods/?nc=nb" role="none">Snacks &amp; Branded
                                        Foods</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/beauty-hygiene/?nc=nb" role="none">Beauty &amp; Hygiene</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/cleaning-household/?nc=nb" role="none">Cleaning &amp; Household</a>
                                </li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/kitchen-garden-pets/?nc=nb" role="none">Kitchen, Garden &amp; Pets</a>
                                </li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/eggs-meat-fish/?nc=nb" role="none">Eggs, Meat &amp; Fish</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK"
                                        href="/cl/gourmet-world-food/?nc=nb" role="none">Gourmet &amp; World Food</a>
                                </li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink-sc-8wbym9-0 gTvqBK" href="/cl/baby-care/?nc=nb"
                                        role="none">Baby Care</a></li>
                            </ul>
                            <ul class="jsx-1259984711 w-56 px-2.5 bg-silverSurfer-200 text-darkOnyx-800" role="none">
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 hggaA"
                                        href="/pc/fruits-vegetables/cuts-sprouts/?nc=nb" role="none">Cuts &amp;
                                        Sprouts</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/exotic-fruits-veggies/?nc=nb" role="none">Exotic
                                        Fruits &amp; Veggies</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/flower-bouquets-bunches/?nc=nb" role="none">Flower
                                        Bouquets, Bunches</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/fresh-fruits/?nc=nb" role="none">Fresh Fruits</a>
                                </li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/fresh-vegetables/?nc=nb" role="none">Fresh
                                        Vegetables</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/herbs-seasonings/?nc=nb" role="none">Herbs &amp;
                                        Seasonings</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink2-sc-8wbym9-1 mLodv"
                                        href="/pc/fruits-vegetables/organic-fruits-vegetables/?nc=nb"
                                        role="none">Organic Fruits &amp; Vegetables</a></li>
                            </ul>
                            <ul class="jsx-1259984711 w-56 px-2.5 bg-white text-darkOnyx-800 rounded-r-xs" role="none">
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink3-sc-8wbym9-2 kuLxIQ"
                                        href="/pc/fruits-vegetables/cuts-sprouts/cut-peeled-veggies/?nc=nb"
                                        role="none">Cut &amp; Peeled Veggies</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink3-sc-8wbym9-2 kTPRNM"
                                        href="/pc/fruits-vegetables/cuts-sprouts/cut-fruit-tender-coconut/?nc=nb"
                                        role="none">Cut Fruit, Tender Coconut</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink3-sc-8wbym9-2 kTPRNM"
                                        href="/pc/fruits-vegetables/cuts-sprouts/fresh-salads-sprouts/?nc=nb"
                                        role="none">Fresh Salads &amp; Sprouts</a></li>
                                <li class="jsx-1259984711" role="none"><a
                                        class="CategoryTree___StyledLink3-sc-8wbym9-2 kTPRNM"
                                        href="/pc/fruits-vegetables/cuts-sprouts/recipe-packs/?nc=nb" role="none">Recipe
                                        Packs</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="Backdrop___StyledDiv2-sc-1mhwh2y-1 dokyde"></div>
        </div>
        <div class="TopNav___StyledDiv-sc-1vxbycn-0 iDyRZn">
            <ul class="grid grid-flow-col p-1 lg:gap-x-7.5 xl:gap-x-11.5">
                <li class="text-center lg:w-28 xl:w-24.5  text-md leading-md"><a
                        class="inline-flex p-1.5 relative max-w-32 overflow-hidden"
                        href="https://www.bigbasket.com/pc/fruits-vegetables/exotic-fruits-veggies/"><span
                            class="Label-sc-15v1nk5-0 gJxZPQ truncate bg-gradient-to-t from-rossoCorsa-100 via-white to-white text-rossoCorsa-500">Exotic
                            Fruits &amp; Veggies</span>
                        <div class="TopNav___StyledMotionDiv-sc-1vxbycn-1 grzXPS"><span
                                class="TopNav___StyledMotionSpan-sc-1vxbycn-2 gcPbqq">Exotic Fruits &amp; Veggies</span>
                        </div>
                    </a></li>
                <li class="text-center lg:w-28 xl:w-24.5  text-md leading-md"><a
                        class="inline-flex p-1.5 relative max-w-32 overflow-hidden"
                        href="https://www.bigbasket.com/pc/beverages/tea/"><span
                            class="Label-sc-15v1nk5-0 gJxZPQ truncate bg-gradient-to-t from-rossoCorsa-100 via-white to-white text-rossoCorsa-500">Tea</span>
                        <div class="TopNav___StyledMotionDiv-sc-1vxbycn-1 grzXPS"><span
                                class="TopNav___StyledMotionSpan-sc-1vxbycn-2 gcPbqq">Tea</span></div>
                    </a></li>
                <li class="text-center lg:w-28 xl:w-24.5  text-md leading-md"><a
                        class="inline-flex p-1.5 relative max-w-32 overflow-hidden"
                        href="https://www.bigbasket.com/pc/foodgrains-oil-masala/edible-oils-ghee/ghee-vanaspati/"><span
                            class="Label-sc-15v1nk5-0 gJxZPQ truncate bg-gradient-to-t from-rossoCorsa-100 via-white to-white text-rossoCorsa-500">Ghee</span>
                        <div class="TopNav___StyledMotionDiv-sc-1vxbycn-1 grzXPS"><span
                                class="TopNav___StyledMotionSpan-sc-1vxbycn-2 gcPbqq">Ghee</span></div>
                    </a></li>
                <li class="text-center lg:w-28 xl:w-24.5  text-md leading-md"><a
                        class="inline-flex p-1.5 relative max-w-32 overflow-hidden"
                        href="https://www.bigbasket.com/pb/nandini/"><span
                            class="Label-sc-15v1nk5-0 gJxZPQ truncate bg-gradient-to-t from-rossoCorsa-100 via-white to-white text-rossoCorsa-500">Nandini</span>
                        <div class="TopNav___StyledMotionDiv-sc-1vxbycn-1 grzXPS"><span
                                class="TopNav___StyledMotionSpan-sc-1vxbycn-2 gcPbqq">Nandini</span></div>
                    </a></li>
            </ul>
            <div class="relative"><button class="h-full px-0 py-1.5" id="headlessui-menu-button-:r2:" type="button"
                    aria-haspopup="true" aria-expanded="false" data-headlessui-state=""><svg width="16" height="16"
                        xmlns="http://www.w3.org/2000/svg" fill="false" class="cursor-pointer">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                            d="m9.3 3.582 3.22 4c.199.247.196.6-.008.845l-3.333 4a.666.666 0 1 1-1.024-.854l2.984-3.58-2.877-3.575A.666.666 0 1 1 9.3 3.582ZM3.698 3.48a.667.667 0 0 1 .937.101l3.219 4c.198.247.196.6-.008.845l-3.333 4a.666.666 0 1 1-1.024-.854l2.983-3.58-2.876-3.575a.667.667 0 0 1 .102-.937Z">
                        </path>
                    </svg></button></div>
            <div class="w-0 place-self-center h-6 border-r border-silverSurfer-200"></div>
        </div>
        <div class="grid grid-flow-col gap-x-5.5 w-36.5 place-content-center"><a
                href="https://www.bigbasket.com/offers/?nc=b-header-2-tile&amp;b_t=header-2-tile&amp;b_camp=hp_cmc_m_offer_28_220921_all"><img
                    width="74" height="28"
                    src="http://www.bigbasket.com/media/uploads/banner_images/hp_cmc_m_offer_28_220921_all.png"
                    alt="banners"></a></div>
    </div>
</body>

</html>